In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
0,1,60,162,558,5336,1280,891,247,31,111,...,0,460,0,4056,3216,740,0.239880,0.300207,0.360195,0.660402
1,3,86,161,677,5620,1492,1147,216,46,83,...,0,531,0,4128,3376,643,0.265480,0.328890,0.364591,0.693480
2,5,79,162,679,5550,1496,1088,262,63,83,...,0,543,0,4054,3175,710,0.269550,0.334646,0.384324,0.718971
3,7,96,162,780,5536,1458,990,265,40,163,...,0,561,0,4078,3145,682,0.263367,0.331146,0.414017,0.745164
4,9,96,162,688,5441,1354,905,247,21,181,...,55,597,35,4087,2703,548,0.248851,0.321258,0.401764,0.723022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,1153,71,162,680,5592,1429,1037,205,29,158,...,0,471,0,4163,3370,826,0.255544,0.313376,0.387339,0.700715
577,1155,76,162,750,5518,1380,871,287,28,194,...,81,680,25,4138,2803,907,0.250091,0.331030,0.417724,0.748754
578,1157,83,162,836,5568,1526,1037,288,39,162,...,75,551,57,4042,3116,867,0.274066,0.336302,0.427083,0.763385
579,1159,67,162,758,5517,1507,1028,278,59,142,...,0,388,0,4010,3066,967,0.273156,0.320914,0.422150,0.743064
580,1161,67,162,667,5491,1353,850,311,27,165,...,64,516,49,4138,3145,773,0.246403,0.308620,0.403023,0.711643

In [ ]:
df.shape # this tell how big is the data , basically it tells us the rows and columns

(581, 24)

In [ ]:
df.head() # this tells us the top 5 rows of our data set

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
0,1,60,162,558,5336,1280,891,247,31,111,...,0,460,0,4056,3216,740,0.239880,0.300207,0.360195,0.660402
1,3,86,161,677,5620,1492,1147,216,46,83,...,0,531,0,4128,3376,643,0.265480,0.328890,0.364591,0.693480
2,5,79,162,679,5550,1496,1088,262,63,83,...,0,543,0,4054,3175,710,0.269550,0.334646,0.384324,0.718971
3,7,96,162,780,5536,1458,990,265,40,163,...,0,561,0,4078,3145,682,0.263367,0.331146,0.414017,0.745164
4,9,96,162,688,5441,1354,905,247,21,181,...,55,597,35,4087,2703,548,0.248851,0.321258,0.401764,0.723022

In [ ]:
df.sample(5) # this fetches 5 random rows and columns

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
191,383,74,162,645,5452,1330,907,280,29,114,...,50,559,57,4122,3028,679,0.243947,0.311305,0.368672,0.679977
530,1061,61,162,513,5409,1274,930,227,16,101,...,39,498,40,4135,2951,698,0.235533,0.297965,0.339434,0.637400
1,3,86,161,677,5620,1492,1147,216,46,83,...,0,531,0,4128,3376,643,0.265480,0.328890,0.364591,0.693480
155,311,68,161,603,5446,1316,977,193,53,93,...,0,534,0,4130,3360,681,0.241645,0.309365,0.347778,0.657143
421,843,86,162,736,5542,1456,1003,285,18,150,...,50,591,40,4086,3059,641,0.262721,0.331605,0.401840,0.733446

In [ ]:
df.info() # this gives the categorical data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581 entries, 0 to 580
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          581 non-null    int64
 1   W           581 non-null    int64
 2   G           581 non-null    int64
 3   R           581 non-null    int64
 4   AB          581 non-null    int64
 5   H           581 non-null    int64
 6   1B          581 non-null    int64
 7   2B          581 non-null    int64
 8   3B          581 non-null    int64
 9   HR          581 non-null    int64
 10  BB          581 non-null    int64
 11  SO          581 non-null    int64
 12  SB          581 non-null    int64
 13  CS          581 non-null    int64
 14  HBP         581 non-null    int64
 15  BBHBP       581 non-null    int64
 16  SF          581 non-null    int64
 17  Outs        581 non-null    int64
 18  Outsinplay  581 non-null    int64
 19  RA          581 non-null    int64
 20  BA          581 non-null    float64
 21  OBA         581 non-null    float64
 22  SLG         581 non-null    float64
 23  OPS         581 non-null    float64
dtypes: float64(4), int64(20)
memory usage: 109.1 KB

In [ ]:
df.isnull().sum() # this tells the missing values in the columns

ID            0
W             0
G             0
R             0
AB            0
H             0
1B            0
2B            0
3B            0
HR            0
BB            0
SO            0
SB            0
CS            0
HBP           0
BBHBP         0
SF            0
Outs          0
Outsinplay    0
RA            0
BA            0
OBA           0
SLG           0
OPS           0
dtype: int64

In [ ]:
df.describe() # this gives the mathematical description of the data

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
count,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,...,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000
mean,581.000000,79.413081,158.969019,713.099828,5432.340792,1419.020654,976.506024,262.604131,32.425129,147.485370,...,21.846816,544.079174,17.323580,4013.320138,3043.872633,713.444062,0.261091,0.327273,0.402523,0.729796
std,335.729057,12.536626,11.372186,100.936394,396.338140,130.178377,93.027538,42.435244,10.146172,40.995229,...,28.656809,82.461301,22.231198,290.986155,253.618335,104.803539,0.012078,0.014118,0.032048,0.043866
min,1.000000,37.000000,103.000000,329.000000,3493.000000,797.000000,576.000000,119.000000,11.000000,49.000000,...,0.000000,278.000000,0.000000,2601.000000,2022.000000,343.000000,0.226356,0.284100,0.326515,0.614404
25%,291.000000,71.000000,162.000000,647.000000,5462.000000,1369.000000,937.000000,237.000000,25.000000,116.000000,...,0.000000,495.000000,0.000000,4044.000000,2952.000000,651.000000,0.252307,0.317614,0.378841,0.699169
50%,581.000000,80.000000,162.000000,712.000000,5518.000000,1432.000000,989.000000,267.000000,31.000000,147.000000,...,0.000000,544.000000,0.000000,4085.000000,3072.000000,710.000000,0.261026,0.326602,0.401113,0.728662
75%,871.000000,89.000000,162.000000,783.000000,5583.000000,1499.000000,1037.000000,289.000000,38.000000,176.000000,...,50.000000,597.000000,41.000000,4115.000000,3207.000000,779.000000,0.269683,0.336702,0.425832,0.758919
max,1161.000000,116.000000,164.000000,993.000000,5781.000000,1684.000000,1193.000000,376.000000,67.000000,257.000000,...,103.000000,802.000000,70.000000,4212.000000,3447.000000,1103.000000,0.292515,0.363665,0.483839,0.845694

In [ ]:
df.duplicated().sum() # this tells how many rows are duplicated

np.int64(0)

In [ ]:
df.corr() # this gives the correlation of all the columns

,ID,W,G,R,AB,H,1B,2B,3B,HR,...,HBP,BBHBP,SF,Outs,Outsinplay,RA,BA,OBA,SLG,OPS
ID,1.000000,-0.050068,-0.039021,0.001224,-0.030361,-0.008924,-0.007427,-0.029105,-0.005586,0.020027,...,0.011687,-0.031468,0.008890,-0.037362,-0.016211,0.067605,0.032323,0.014044,0.027266,0.024441
W,-0.050068,1.000000,0.467837,0.613683,0.493352,0.583387,0.454535,0.382941,0.108545,0.397816,...,0.122171,0.499463,0.133205,0.410981,0.360894,-0.212342,0.378542,0.457977,0.379208,0.424447
G,-0.039021,0.467837,1.000000,0.510911,0.980376,0.777543,0.712409,0.485842,0.190109,0.302474,...,0.199423,0.512944,0.204699,0.987474,0.790476,0.478936,-0.000429,0.021311,0.059621,0.050418
R,0.001224,0.613683,0.510911,1.000000,0.612702,0.841048,0.490924,0.732230,0.064637,0.782740,...,0.255491,0.673377,0.276711,0.458272,0.284480,0.519989,0.701738,0.770832,0.814684,0.843297
AB,-0.030361,0.493352,0.980376,0.612702,1.000000,0.865956,0.764112,0.570992,0.198093,0.375781,...,0.210819,0.528154,0.223752,0.974649,0.781806,0.529896,0.143587,0.134714,0.180554,0.175270
H,-0.008924,0.583387,0.777543,0.841048,0.865956,1.000000,0.830386,0.700881,0.220504,0.511043,...,0.179880,0.519287,0.214207,0.732107,0.636265,0.542430,0.617696,0.536774,0.527185,0.557920
1B,-0.007427,0.454535,0.712409,0.490924,0.764112,0.830386,1.000000,0.259708,0.292198,0.026473,...,-0.146156,0.261817,-0.107542,0.669270,0.807263,0.321857,0.442209,0.293133,0.053953,0.133762
2B,-0.029105,0.382941,0.485842,0.732230,0.570992,0.700881,0.259708,1.000000,0.014607,0.597534,...,0.526782,0.524322,0.552098,0.464167,0.141658,0.503413,0.489632,0.498863,0.675309,0.653937
3B,-0.005586,0.108545,0.190109,0.064637,0.198093,0.220504,0.292198,0.014607,1.000000,-0.225481,...,-0.207794,-0.115806,-0.180736,0.171166,0.300579,0.024244,0.122180,-0.021046,-0.052091,-0.044831
HR,0.020027,0.397816,0.302474,0.782740,0.375781,0.511043,0.026473,0.597534,-0.225481,1.000000,...,0.409006,0.540770,0.397482,0.283209,-0.032462,0.464996,0.420919,0.528137,0.865482,0.802299
BB,-0.038988,0.501492,0.486826,0.641494,0.499170,0.501239,0.343039,0.374474,-0.047837,0.437436,...,0.077009,0.938055,0.088389,0.455656,0.305811,0.302328,0.208294,0.610298,0.321741,0.431485
SO,-0.036752,0.152548,0.472214,0.332714,0.463879,0.280867,-0.054301,0.538957,-0.143658,0.492767,...,0.604570,0.482727,0.593214,0.506176,-0.144534,0.387382,-0.169320,-0.008819,0.257407,0.185223
SB,-0.042408,0.141734,0.154672,0.003590,0.125554,0.065434,0.183240,-0.087394,0.325358,-0.198093,...,-0.200809,-0.072689,-0.186781,0.141738,0.169421,-0.076250,-0.066597,-0.119584,-0.182575,-0.171877
CS,-0.031413,-0.034049,0.122553,-0.148987,0.071988,-0.000700,0.260225,-0.320967,0.341568,-0.345026,...,-0.488733,-0.200787,-0.504956,0.098365,0.324421,-0.047040,-0.115029,-0.197833,-0.343565,-0.314680
HBP,0.011687,0.122171,0.199423,0.255491,0.210819,0.179880,-0.146156,0.526782,-0.207794,0.409006,...,1.000000,0.417696,0.932302,0.206674,-0.201363,0.225402,0.023176,0.142796,0.331333,0.288030
BBHBP,-0.031468,0.499463,0.512944,0.673377,0.528154,0.519287,0.261817,0.524322,-0.115806,0.540770,...,0.417696,1.000000,0.404540,0.487059,0.208706,0.353840,0.197871,0.605784,0.408344,0.493305
SF,0.008890,0.133205,0.204699,0.276711,0.223752,0.214207,-0.107542,0.552098,-0.180736,0.397482,...,0.932302,0.404540,1.000000,0.208932,-0.190535,0.226666,0.069477,0.160401,0.345662,0.304165
Outs,-0.037362,0.410981,0.987474,0.458272,0.974649,0.732107,0.669270,0.464167,0.171166,0.283209,...,0.206674,0.487059,0.208932,1.000000,0.780215,0.479079,-0.080766,-0.056649,0.010077,-0.010870
Outsinplay,-0.016211,0.360894,0.790476,0.284480,0.781806,0.636265,0.807263,0.141658,0.300579,-0.032462,...,-0.201363,0.208706,-0.190535,0.780215,1.000000,0.268702,0.030141,-0.058599,-0.175133,-0.146812
RA,0.067605,-0.212342,0.478936,0.519989,0.529896,0.542430,0.321857,0.503413,0.024244,0.464996,...,0.225402,0.353840,0.226666,0.479079,0.268702,1.000000,0.243447,0.238439,0.385663,0.358506
BA,0.032323,0.378542,-0.000429,0.701738,0.143587,0.617696,0.442209,0.489632,0.122180,0.420919,...,0.023176,0.197871,0.069477,-0.080766,0.030141,0.243447,1.000000,0.853847,0.762610,0.831969
OBA,0.014044,0.457977,0.021311,0.770832,0.134714,0.536774,0.293133,0.498863,-0.021046,0.528137,...,0.142796,0.605784,0.160401,-0.056649,-0.058599,0.238439,0.853847,1.000000,0.771113,0.885220
SLG,0.027266,0.379208,0.059621,0.814684,0.180554,0.527185,0.053953,0.675309,-0.052091,0.865482,...,0.331333,0.408344,0.345662,0.010077,-0.175133,0.385663,0.762610,0.771113,1.000000,0.978779
OPS,0.024441,0.424447,0.050418,0.843297,0.175270,0.557920,0.133762,0.653937,-0.044831,0.802299,...,0.288030,0.493305,0.304165,-0.010870,-0.146812,0.358506,0.831969,0.885220,0.978779,1.000000

In [ ]:
df.corr()['ID'] # this gives the correlation of ID row/column with everyone

ID            1.000000
W            -0.050068
G            -0.039021
R             0.001224
AB           -0.030361
H            -0.008924
1B           -0.007427
2B           -0.029105
3B           -0.005586
HR            0.020027
BB           -0.038988
SO           -0.036752
SB           -0.042408
CS           -0.031413
HBP           0.011687
BBHBP        -0.031468
SF            0.008890
Outs         -0.037362
Outsinplay   -0.016211
RA            0.067605
BA            0.032323
OBA           0.014044
SLG           0.027266
OPS           0.024441
Name: ID, dtype: float64